@tool
extends EditorInspectorPlugin

const BakerScript := preload("uid://dui3gn00322hh")
const SettingsScript := preload("uid://c5i7h2p7ixlc4")

const MUTED_COLOR := Color(0.65, 0.65, 0.65)
const NEUTRAL_COLOR := Color(0.75, 0.75, 0.75)
const SUCCESS_COLOR := Color(0.65, 0.9, 0.65)
const ERROR_COLOR := Color(1.0, 0.45, 0.45)

func _can_handle(object: Object) -> bool:
	return object is TileMapLayer

func _parse_begin(object: Object) -> void:
	var tile_map := object as TileMapLayer
	
	if tile_map == null:
		return
		
	var container := VBoxContainer.new()
	container.add_theme_constant_override("separation", 6)
	
	container.add_child(HSeparator.new())
	
	var title := Label.new()
	title.text = "Tilemap Baker"
	title.add_theme_font_size_override("font_size", 14)
	container.add_child(title)
	
	container.add_child(_create_physics_layers_display(tile_map))
	
	var spacer := Control.new()
	spacer.custom_minimum_size.y = 4
	container.add_child(spacer)
	
	var status := Label.new()
	status.autowrap_mode = TextServer.AUTOWRAP_WORD_SMART
	status.modulate = SUCCESS_COLOR
	
	var bake_button := Button.new()
	bake_button.text = "Bake Collision"
	bake_button.tooltip_text = "Generate merged collision shapes from all TileSet physics layers."
	bake_button.custom_minimum_size.y = 32
	bake_button.pressed.connect(_bake_pressed.bind(tile_map, status))
	container.add_child(bake_button)
	
	var clear_button := Button.new()
	clear_button.text = "Clear Baked Collision"
	clear_button.tooltip_text = "Remove collision previously generated by da baker."
	clear_button.pressed.connect(_clear_pressed.bind(tile_map, status))
	container.add_child(clear_button)
	
	container.add_child(status)
	
	add_custom_control(container)

func _create_physics_layers_display(tile_map: TileMapLayer) -> Control:
	var container := VBoxContainer.new()
	container.add_theme_constant_override("separation", 4)
	
	var tile_set := tile_map.tile_set
	
	if tile_set == null:
		return container
		
	var header := Label.new()
	header.text = "Physics Layers"
	header.add_theme_font_size_override("font_size", 13)
	container.add_child(header)
	
	var layer_count := tile_set.get_physics_layers_count()
	
	if layer_count == 0:
		var empty_label := Label.new()
		empty_label.text = "No physics layers configured."
		empty_label.modulate = ERROR_COLOR
		container.add_child(empty_label)
		return container
	
	var count_label := Label.new()
	count_label.text = "%d physics layer%s detected" % [
		layer_count,
		"" if layer_count == 1 else "s",
	]
	count_label.modulate = MUTED_COLOR
	container.add_child(count_label)
	
	var shared_label := Label.new()
	shared_label.text = "Names and colors are shared by every TileMapLayer in this project."
	shared_label.autowrap_mode = TextServer.AUTOWRAP_WORD_SMART
	shared_label.modulate = MUTED_COLOR
	container.add_child(shared_label)
	
	for physics_layer in range(layer_count):
		container.add_child(_create_physics_layer_row(tile_set, physics_layer))
		
	return container

func _create_physics_layer_row(
	tile_set: TileSet,
	physics_layer: int
) -> Control:
	var color := SettingsScript.get_layer_color(physics_layer)
	
	var style := StyleBoxFlat.new()
	style.bg_color = Color(0.0, 0.0, 0.0, 0.2)
	style.border_color = color
	style.border_width_left = 4
	style.set_corner_radius_all(3)
	style.set_content_margin_all(8)
	style.content_margin_left = 12
	
	var panel := PanelContainer.new()
	panel.add_theme_stylebox_override("panel", style)
	
	var rows := VBoxContainer.new()
	rows.add_theme_constant_override("separation", 4)
	panel.add_child(rows)
	
	var header_row := HBoxContainer.new()
	rows.add_child(header_row)
	
	var layer_label := Label.new()
	layer_label.text = "Physics Layer %d" % physics_layer
	layer_label.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	header_row.add_child(layer_label)
	
	var color_button := ColorPickerButton.new()
	color_button.color = color
	color_button.edit_alpha = false
	color_button.custom_minimum_size = Vector2(44, 0)
	color_button.tooltip_text = "Color used for this layer's collision shapes."
	color_button.color_changed.connect(
		_layer_color_changed.bind(physics_layer, style)
	)
	color_button.popup_closed.connect(_save_settings)
	header_row.add_child(color_button)
	
	var name_row := HBoxContainer.new()
	rows.add_child(name_row)
	
	var name_label := Label.new()
	name_label.text = "Name"
	name_label.custom_minimum_size.x = 55
	name_row.add_child(name_label)
	
	var name_edit := LineEdit.new()
	name_edit.placeholder_text = "Physics Layer %d" % physics_layer
	name_edit.text = SettingsScript.get_layer_name(physics_layer)
	name_edit.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	name_edit.tooltip_text = "Name used for the generated collision body in every scene."
	name_edit.text_changed.connect(_layer_name_changed.bind(physics_layer))
	name_edit.text_submitted.connect(_save_settings.unbind(1))
	name_edit.focus_exited.connect(_save_settings)
	name_row.add_child(name_edit)
	
	var info := Label.new()
	info.text = "Layer: %d    Mask: %d" % [
		tile_set.get_physics_layer_collision_layer(physics_layer),
		tile_set.get_physics_layer_collision_mask(physics_layer),
	]
	info.modulate = MUTED_COLOR
	rows.add_child(info)
	
	return panel

func _layer_name_changed(new_name: String, physics_layer: int) -> void:
	SettingsScript.set_layer_name(physics_layer, new_name)

func _layer_color_changed(
	new_color: Color,
	physics_layer: int,
	style: StyleBoxFlat
) -> void:
	SettingsScript.set_layer_color(physics_layer, new_color)
	style.border_color = new_color

func _save_settings() -> void:
	SettingsScript.save()

func _bake_pressed(tile_map: TileMapLayer, status: Label) -> void:
	if tile_map == null:
		return
		
	var result := BakerScript.bake(tile_map)
	
	if not result["success"]:
		status.text = "Bake failed. Check the Output panel."
		status.modulate = ERROR_COLOR
		return
		
	var layers: Array = result["layers"]
	var total_cells := 0
	var total_rectangles := 0
	var active_layers := 0
	
	for layer_data: Dictionary in layers:
		var cells: int = layer_data["cells"]
		var rectangles: int = layer_data["rectangles"]
		
		total_cells += cells
		total_rectangles += rectangles
		
		if cells > 0:
			active_layers += 1
	
	status.text = (
		"Baked %d physics layer%s\n%d active layer%s • %d cells → %d rectangles"
		% [
			layers.size(),
			"" if layers.size() == 1 else "s",
			active_layers,
			"" if active_layers == 1 else "s",
			total_cells,
			total_rectangles,
		]
	)
	status.modulate = SUCCESS_COLOR
	
	EditorInterface.mark_scene_as_unsaved()

func _clear_pressed(tile_map: TileMapLayer, status: Label) -> void:
	if tile_map == null:
		return
	
	BakerScript.clear(tile_map)
	
	status.text = "Baked collision cleared."
	status.modulate = NEUTRAL_COLOR
	
	EditorInterface.mark_scene_as_unsaved()
